[tool.poetry]
name = "renaminator"
version = "0.1.0"
description = "A file renaming utility"
authors = ["Tsierenana BÃ´tramanagna Gracy <gtsierenana@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.scripts]
renaminator = "renaminator.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
